# use Ganache's forked mainnet mode as the default network
# NOTE: You don't *have* to do this, but it is often helpful for testing
networks:
  default: mainnet-fork

# automatically fetch contract sources from Etherscan
autofetch_sources: True

# require OpenZepplin Contracts
dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.9.3

# path remapping to support imports from GitHub/NPM
compiler:
  solc:
    version:
    remappings:
      - "@openzeppelin/contracts@4.9.3=OpenZeppelin/openzeppelin-contracts@4.9.3/contracts"

reports:
  exclude_contracts:
    - Owned
    - Pausable
    - RewardsDistributionRecipient
    - IStakingRewards
    - SafeMath
    - SafeERC20
    - Ownable
    - Address
