# use Ganache's forked mainnet mode as the default network
# NOTE: You don't *have* to do this, but it is often helpful for testing
networks:
  default: optimism-yearn-fork

# automatically fetch contract sources from Etherscan
autofetch_sources: True

# require OpenZepplin Contracts
dependencies:
  - OpenZeppelin/openzeppelin-contracts@2.3.0
  - OpenZeppelin/openzeppelin-contracts@4.7.1

# path remapping to support imports from GitHub/NPM
compiler:
  solc:
    version:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@2.3.0"
      - "@openzeppelin_new=OpenZeppelin/openzeppelin-contracts@4.7.1"

reports:
  exclude_contracts:
    - Owned
    - Pausable
    - RewardsDistributionRecipient
    - IStakingRewards
    - SafeMath
    - SafeERC20
    - Ownable
    - Address
